# -*- coding: utf-8 -*-
"""houseprediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1awg_0ob_gYp2rfBMHHcola579DxeMcS-
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("train.csv")
df.head()

df[['GrLivArea', 'BedroomAbvGr', 'FullBath', 'SalePrice']].head()

X = df[['GrLivArea', 'BedroomAbvGr', 'FullBath']]  # variables indépendantes
y = df['SalePrice']  # variable cible

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score

print("Erreur quadratique moyenne (MSE) :", mean_squared_error(y_test, y_pred))
print("Score R² :", r2_score(y_test, y_pred))

import matplotlib.pyplot as plt

plt.scatter(y_test, y_pred, alpha=0.5)
plt.xlabel("Prix réels")
plt.ylabel("Prix prédits")
plt.title("Prix des maisons : réels vs prédits")
plt.show()

!pip install gradio

import gradio as gr
import pandas as pd
from sklearn.linear_model import LinearRegression

# Charger les données et entraîner le modèle
df = pd.read_csv("train.csv")
X = df[['GrLivArea', 'BedroomAbvGr', 'FullBath']]
y = df['SalePrice']
model = LinearRegression().fit(X, y)

# Fonction de prédiction
def predict_price(gr_liv_area, bedroom, full_bath):
    input_data = [[gr_liv_area, bedroom, full_bath]]
    prediction = model.predict(input_data)[0]
    return f"🏡 Prix estimé : **{round(prediction)} $**"

# Interface Gradio avancée
with gr.Blocks() as demo:
    gr.Markdown("# 🏠 Estimation de prix immobilier\nDonnez les détails ci-dessous pour estimer le prix.")

    with gr.Row():
        gr_liv_area = gr.Slider(500, 4500, label="Surface habitable (GrLivArea)")
        bedroom = gr.Slider(0, 10, step=1, label="Nombre de chambres (BedroomAbvGr)")
        full_bath = gr.Slider(0, 5, step=1, label="Salles de bain (FullBath)")

    predict_btn = gr.Button("Prédire le prix 🧮")
    output = gr.Markdown()

    predict_btn.click(fn=predict_price, inputs=[gr_liv_area, bedroom, full_bath], outputs=output)

demo.launch()

